const i18nData = {
      ja: {
        navHome: "トップ・概要",
        navAccess: "アクセス・移動",
        navCheckin: "チェックイン方法",
        navWifi: "Wi-Fi & 設備",
        navRules: "ハウスルール",
        navNearby: "周辺検索・マップ",
        navCheckout: "チェックアウト",
        navFaq: "FAQ & 緊急ヘルプ",

        heroBadge: "ゲストポータル Webガイド",
        heroTitle: "フォルモント住之江 101 へようこそ！",
        heroDesc: "快適な大阪滞在をお楽しみください。アクセス、鍵の解錠、チェックイン手続き、Wi-Fi情報、周辺マップをまとめた公式案内サイトです。",

        quickTaxi: "タクシー画面",
        quickWifi: "Wi-Fi情報",
        quickCheckin: "鍵＆チェックイン",
        quickHelp: "困ったとき",

        smartCheckinTitle: "💡【強く推奨】事前登録（スマートチェックイン）",
        smartCheckinSub: "当日の部屋タブレットの入力時間を大幅短縮できます",
        smartCheckinDesc: "日本の法令により全宿泊者の情報登録が必要です。事前メッセージに添付されている「スマートチェックイン案内URL / QRコード」より、ご自宅や移動中に事前入力をお済ませいただくと、当日スムーズに入室いただけます。",

        accessTitle: "施設へのアクセス & 移動方法",
        accessSub: "Address & Transport Guide",
        lblAddress: "📍 所在地",
        btnOpenMap: "マップを表示",
        btnPhotoGuide: "写真付き道順ガイド",
        lblTrain: "🚃 最寄り駅＆関西空港からのアクセス",
        kixRouteTitle: "関西国際空港（KIX）からのルート:",
        kixRouteDesc: "南海電鉄「ラピート」または「空港急行」で「天下茶屋（てんがちゃや）駅」へ。天下茶屋駅で各駅停車にお乗り換えの上、「粉浜駅」または「住吉大社駅」でお降りください。",
        lblTransitGuide: "⏱ 主要スポットへの所要時間目安",
        carWarnTitle: "お車でお越しの方へ（重要）:",
        carWarnDesc: "当施設には専用駐車場がございません。また前面道路は非常に狭く駐停車厳禁です。お車でお越しの際は必ず近隣のコインパーキングをご利用ください。",
        lblKeyCode: "🔑 キーボックスの暗証番号について",
        lblKeyNotice: "The lockbox passcode will be sent to you via message prior to your check-in date.",
        btnCheckinGuide: "Lockbox Photo Guide",
        step2Title: "2. Unlock Room Door",
        step2Desc: "Use key to unlock Room 101. Please remove your shoes at the entrance.",
        lockWarnTitle: "NOT Auto-locking:",
        lockWarnDesc: "Please manually lock the door with the key whenever you leave.",
        step3Title: "3. [REQUIRED] Tablet Check-in in Living Room",
        step3Desc: "Immediately after entering, complete check-in & passport verification on the living room tablet (maneKEY).",
        step3Tip: "*Pre-registered guests can simply scan their QR code on the tablet camera.",

        wifiTitle: "Wi-Fi Information",
        wifiSub: "Free High-Speed Wi-Fi",
        lblSsid5G: "SSID (5GHz - Fast)",
        lblSsid24G: "SSID (2.4GHz)",
        lblWifiPassword: "Wi-Fi Password",
        btnCopy: "Copy",

        rulesTitle: "House Rules",
        rulesSub: "Important Rules for Your Stay",
        rulePenaltyTitle: "Penalty Fee (30,000 JPY):",
        rulePenaltyDesc: "Violations or noise complaints from neighbors will result in a 30,000 JPY fee & immediate eviction.",
        rule1Title: "Strictly No Smoking",
        rule1Desc: "Smoking (including e-cigarettes) is prohibited in rooms, balcony, and all building premises.",
        rule2Title: "Quiet Hours after 20:00",
        rule2Desc: "No parties. Keep noise, TV, and talking volume low at night to respect neighbors.",
        rule3Title: "No Shoes Inside",
        rule3Desc: "Please take off shoes at the entrance as per Japanese custom.",
        rule4Title: "Registered Guests Only",
        rule4Desc: "Unregistered visitors are strictly forbidden from entering or staying.",

        nearbyTitle: "Nearby Map & Search",
        nearbySub: "Neighborhood & Parking Guide",
        btnGoogleMyMap: "Open Area Guide Map (Google My Maps)",
        placeParkTitle: "Nearby Coin Parking",
        placeParkTag: "No private parking available",
        placeParkDesc: "Please use nearby paid coin parking spaces if traveling by car.",
        btnSearchPark: "Search Parking",
        placeSuperTitle: "Supermarket 'Konomi-ya'",
        placeSuperTag: "Groceries & Snacks",
        placeSuperDesc: "Convenient local supermarket for fresh food and snacks (a few mins walk).",
        btnSearchSuper: "Show Route",
        placeStoreTitle: "Convenience Store 'Lawson'",
        placeStoreTag: "24/7 Open & ATM",
        placeStoreDesc: "24h open store for drinks, snacks, and ATM cash withdrawal (short walk).",
        btnSearchStore: "Show Route",
        placeFoodTitle: "Local Food & Dining",
        placeFoodTag: "Takoyaki & Okonomiyaki",
        placeFoodDesc: "Famous Osaka local street food spots nearby in Kohama Arcade (closes ~20:00).",
        btnSearchFood: "Find Restaurants",

        cultureTitle: "🇯🇵 Japan Etiquette Guide",
        cultureSub: "Useful Local Tips",
        cul1Title: "Take off Shoes",
        cul1Desc: "Remove shoes at entryway. Use slippers inside.",
        cul2Title: "No Tipping Needed",
        cul2Desc: "Tipping is not practiced in Japan. Pay only listed prices.",
        cul3Title: "Escalator in Osaka",
        cul3Desc: "Stand on the RIGHT side of escalators in Osaka, leaving left side open.",

        checkoutTitle: "Check-out Process",
        checkoutSub: "Check-out Checklist",
        checkoutTimeTitle: "Check-out Time: By 10:00 AM",
        checkoutTimeDesc: "Please leave on time so cleaning staff can prepare for next guests.",
        checkoutListTitle: "📋 Check-out Checklist",
        coStep1: "Belongings: Check phone chargers, clothes, and log out of Netflix on TV.",
        coStep2: "Power off: Turn off all lights, AC, heaters, and lock all windows.",
        coStep3: "Tablet: Complete 'Check-out' on the living room tablet.",
        coStep4: "Trash: Leave gathered trash inside the room (do not put outside).",
        coStep5: "Lock & Return Key: Lock front door, return key to lockbox and scramble dials.",

        faqTitle: "FAQ & Support",
        faqSub: "Troubleshooting & Support",
        faq1Q: "Q. 滞在中のゴミが溜まった場合はどうすればいいですか？",
        faq1A: "袋にまとめて【建物前の専用ゴミ収集箱】にお出しください。（※日曜日の回収はございませんので、日曜日の排出はお控えください。）",
        faq2Q: "Q. 鍵が開かない・キーボックスの使い方がわからない",
        faq2A: "メッセージでお送りした暗証番号を中央のラインに合わせ、そのまま手前にフタを開けてください（解錠レバーはありません）。",
        faq3Q: "Q. 夜遅く（20:00以降）に到着する場合は？",
        faq3A: "24時間セルフチェックインに対応しておりますので、遅い時間のご到着でも問題ございません。深夜の到着時はスーツケースを持ち上げて運ぶなど、騒音へのご配慮をお願いいたします。",
        btnChatbot: "Open 24/7 Support Chatbot",
        faq1Q: "Q. How to dispose trash during long stay?",
        faq1A: "Put bagged trash into the dedicated box in front of the building (Except Sundays).",
        faq2Q: "Q. Key lockbox doesn't open",
        faq2A: "Align the passcode sent to you in message to the center and open the cover directly.",
        faq3Q: "Q. Late arrival after 20:00?",
        faq3A: "Self check-in is available 24h. Please lift suitcases & keep quiet late at night.",

        sosTitle: "🆘 Emergency Contact & Multilingual Hotline",

        taxiModalTitle: "🚖 Show to Taxi Driver",
        taxiModalDesc: "Show this Japanese address screen to your taxi driver.",
        taxiModalNote: "*Street is narrow, ask driver to stop nearby.",
        btnCopyAddress: "Copy Japanese Address"
      },

      zh: {
        navHome: "首页·概要",
        navAccess: "交通路线",
        navCheckin: "入住指南",
        navWifi: "Wi-Fi与设备",
        navRules: "房屋守则",
        navNearby: "周边搜索地图",
        navCheckout: "退房流程",
        navFaq: "常见问题与救助",

        heroBadge: "住宿指南 Web Portal",
        heroTitle: "欢迎来到 フォルモント住之江 101号室！",
        heroDesc: "祝您在大阪度过愉快的时光！本网站为您提供地址指引、钥匙领取、平板入住、Wi-Fi及周边地图等全套信息。",

        quickTaxi: "出租车用卡",
        quickWifi: "Wi-Fi密码",
        quickCheckin: "钥匙与入住",
        quickHelp: "求助与FAQ",

        smartCheckinTitle: "💡【强烈推荐】预先登记（Smart Check-in）",
        smartCheckinSub: "大幅缩短入住当天在房间平板上的输入时间",
        smartCheckinDesc: "根据日本法律规定，所有住客均需登记身份信息。请在到达前通过预订消息中的链接完成线上预先登记。",

        accessTitle: "交通路线与交通指南",
        accessSub: "Address & Transport Guide",
        lblAddress: "📍 详细地址",
        btnOpenMap: "打开Google地图",
        btnPhotoGuide: "图文带路指南",
        lblTrain: "🚃 最近车站与关西机场路线",
        kixRouteTitle: "关西国际机场 (KIX) 出发路线:",
        kixRouteDesc: "乘坐南海电车特急Rapi:t或空港急行至“天下茶屋站”，换乘南海本线慢车（各站停车），在“粉浜站”或“住吉大社站”下车。",
        lblTransitGuide: "⏱ 前往主要景点预估时间",
        carWarnTitle: "自驾住客请注意（重要）:",
        carWarnDesc: "本设施无专用停车场，且门前道路极窄禁止违章停车。请务必使用附近的收费停车场。",

        checkinTitle: "入住与钥匙领取流程",
        checkinSub: "Self Check-in Process",
        step1Title: "1. 到达并从密码盒中取出钥匙",
        step1Desc: "请在建筑物外的钥匙盒上拨对密码，取出房间钥匙。",
        lblKeyCode: "🔑 钥匙盒密码说明",
        lblKeyNotice: "入住日期临近时，我们将通过预订消息将密码发送给您，请查收。",
        btnCheckinGuide: "钥匙盒位置图文指南",
        step2Title: "2. 用钥匙开门入室",
        step2Desc: "使用钥匙打开101号室。请务必在玄关处脱鞋。",
        lockWarnTitle: "注意：非自动锁",
        lockWarnDesc: "外出及退房时，请务必使用钥匙手动锁门。",
        step3Title: "3.【必须】使用客厅平板登记",
        step3Desc: "进入房间后请首先在客厅平板（maneKEY）上完成全员护照及身份登记。",
        step3Tip: "※已预先登记的住客只需将二维码对准摄像头即可快速完成。",

        wifiTitle: "Wi-Fi 连接信息",
        wifiSub: "Free High-Speed Wi-Fi",
        lblSsid5G: "SSID (5GHz - 高速)",
        lblSsid24G: "SSID (2.4GHz)",
        lblWifiPassword: "Wi-Fi 密码",
        btnCopy: "复制",

        rulesTitle: "房屋守则 (House Rules)",
        rulesSub: "Important House Rules",
        rulePenaltyTitle: "违约金规定（30,000日元）:",
        rulePenaltyDesc: "为避免影响邻居，若发生违规或噪音投诉，将收取违约金并要求立即退房。",
        rule1Title: "全面禁烟",
        rule1Desc: "室内、阳台及楼宇公共区域全禁烟（含电子烟）。",
        rule2Title: "20:00后 保持安静",
        rule2Desc: "严禁派对。夜间请关窗并调低电视和说话音量。",
        rule3Title: "严禁脱鞋进屋",
        rule3Desc: "请遵循日本习惯，在玄关脱鞋后进入室内。",
        rule4Title: "禁止未登记人员入内",
        rule4Desc: "严禁非预订人数之外的访客进入或住宿。",

        nearbyTitle: "周边搜索与停车场",
        nearbySub: "Neighborhood & Parking Guide",
        btnGoogleMyMap: "打开推荐周边地图 (Google My Maps)",
        placeParkTitle: "附近收费停车场",
        placeParkTag: "无专用停车场·禁止路边停车",
        placeParkDesc: "自驾前往时，请利用附近的付费计时停车场。",
        btnSearchPark: "查找附近停车场",
        placeSuperTitle: "Konomi-ya 超市",
        placeSuperTag: "生鲜·食品·日用品",
        placeSuperDesc: "方便采购新鲜食品与当地特色商品的超市（步行数分钟）。",
        btnSearchSuper: "查看路线",
        placeStoreTitle: "罗森便利店 (Lawson)",
        placeStoreTag: "24小时营业·ATM",
        placeStoreDesc: "深夜购物及取款非常方便（步行即达）。",
        btnSearchStore: "查看路线",
        placeFoodTitle: "当地特色美食",
        placeFoodTag: "章鱼烧·御好烧",
        placeFoodDesc: "商店街周边汇集大阪地道美食店（大多20:00打烊）。",
        btnSearchFood: "查找附近美食",

        cultureTitle: "🇯🇵 日本旅行礼仪与小常识",
        cultureSub: "Japan Travel Etiquette Tips",
        cul1Title: "玄关脱鞋",
        cul1Desc: "进屋在玄关脱鞋是日本的传统文化，室内请穿拖鞋或赤脚。",
        cul2Title: "无需付小费",
        cul2Desc: "日本的餐厅和出租车没有给小费的习惯，只支付账单金额即可。",
        cul3Title: "大阪扶梯习惯",
        cul3Desc: "在大阪乘坐自动扶梯时，请站在【右侧】，空出左侧供急行人员通过。",

        checkoutTitle: "退房流程与清单",
        checkoutSub: "Check-out Checklist",
        checkoutTimeTitle: "退房时间: 10:00 AM 前",
        checkoutTimeDesc: "请严格遵守退房时间，以便清洁人员准时整理房间。",
        checkoutListTitle: "📋 退房前检查清单",
        coStep1: "遗留物品: 检查充电器、衣物，并退出电视上的Netflix等账号。",
        coStep2: "关闭电源: 关闭电灯、空调、热水器并锁好所有窗户。",
        coStep3: "平板操作: 在客厅平板上点击“退房(Check-out)”。",
        coStep4: "垃圾处理: 无需拿到室外，归拢在室内垃圾桶即可（清洁员会处理）。",
        coStep5: "锁门与还钥匙: 锁好房门，将钥匙放回室外密码盒并打乱密码。",

        faqTitle: "常见问题与救助",
        faqSub: "Troubleshooting & Support",
        btnChatbot: "打开24小时客服机器人",
        faq1Q: "Q. 连续入住期间垃圾满了怎么办？",
        faq1A: "装袋后放至【楼前的专属垃圾箱】（周日不回收，请勿在周日丢弃）。",
        faq2Q: "Q. 钥匙盒无法打开怎么办？",
        faq2A: "请将消息中收到的密码对准中间，直接拉开盒盖即可。",
        faq3Q: "Q. 20:00以后晚到怎么办？",
        faq3A: "支持24小时自助入住。深夜请注意轻拿行李，避免发出噪音。",

        sosTitle: "🆘 紧急求助与多语言热线",

        taxiModalTitle: "🚖 出租车司机展示画面",
        taxiModalDesc: "请将此画面出示给司机看。",
        taxiModalNote: "*门前道路狭窄，建议让司机在附近方便处停车。",
        btnCopyAddress: "复制日文地址"
      },

      ko: {
        navHome: "홈·개요",
        navAccess: "오시는 길",
        navCheckin: "체크인 방법",
        navWifi: "Wi-Fi & 시설",
        navRules: "하우스 룰",
        navNearby: "주변 검색 지도",
        navCheckout: "체크아웃",
        navFaq: "FAQ & 긴급 도움",

        heroBadge: "게스트 포털 Web 가이드",
        heroTitle: "フォルモント住之江 101에 오신 것을 환영합니다!",
        heroDesc: "편안한 오사카 여행을 즐겨보세요! 위치, 열쇠 해제, 패드 체크인, Wi-Fi 정보, 주변 지도를 안내해 드립니다.",

        quickTaxi: "택시 화면",
        quickWifi: "Wi-Fi 정보",
        quickCheckin: "열쇠 & 체크인",
        quickHelp: "자주 묻는 질문",

        smartCheckinTitle: "💡 [강력 추천] 사전 등록 (스마트 체크인)",
        smartCheckinSub: "당일 객실 태블릿 입력 시간을 크게 단축할 수 있습니다",
        smartCheckinDesc: "일본 법령에 따라 모든 숙박객의 정보 등록이 의무화되어 있습니다. 메시지의 링크를 통해 사전에 입력을 완료해 주세요.",

        accessTitle: "오시는 길 & 교통 가이드",
        accessSub: "Address & Transport Guide",
        lblAddress: "📍 숙소 주소",
        btnOpenMap: "Google 지도 열기",
        btnPhotoGuide: "사진 길안내 가이드",
        lblTrain: "🚃 가까운 역 & 간사이 공항에서 오시는 길",
        kixRouteTitle: "간사이 국제공항(KIX) 출발:",
        kixRouteDesc: "난카이 전철 '라피트' 또는 '공항급행'을 타고 '덴가차야역'으로 이동 후, 난카이 본선 보통열차로 환승하여 '코하마역' 또는 '스미요시타이샤역'에서 하차하세요.",
        lblTransitGuide: "⏱ 주요 관광지 소요 시간",
        carWarnTitle: "차량 이용 게스트 주의사항 (중요):",
        carWarnDesc: "전용 주차장이 없으며 건물 앞 도로는 주정차 금지구역입니다. 반드시 근처의 동전 주차장을 이용해 주세요.",

        checkinTitle: "체크인 & 열쇠 수령 방법",
        checkinSub: "Self Check-in Process",
        step1Title: "1. 도착 및 키박스에서 열쇠 꺼내기",
        step1Desc: "건물 밖에 설치된 키박스의 비밀번호를 맞추고 열쇠를 꺼내세요.",
        lblKeyCode: "🔑 키박스 비밀번호 안내",
        lblKeyNotice: "체크인 날짜가 가까워지면 별도 메시지로 비밀번호를 전송해 드립니다.",
        btnCheckinGuide: "키박스 위치 사진 가이드",
        step2Title: "2. 열쇠로 문을 열고 입실하기",
        step2Desc: "열쇠로 101호 문을 열고 들어오세요. 현관에서 신발을 벗어주세요.",
        lockWarnTitle: "주의: 오토락이 아닙니다",
        lockWarnDesc: "외출 및 퇴실 시에는 반드시 열쇠로 수동 잠금을 해주세요.",
        step3Title: "3. [필수] 거실 태블릿에서 등록 절차",
        step3Desc: "입실 후 가장 먼저 거실에 비치된 태블릿(maneKEY)으로 모든 숙박객의 등록을 완료해 주세요.",
        step3Tip: "*사전 등록을 완료하신 분은 화면의 QR코드를 카메라에 대기만 하면 됩니다.",

        wifiTitle: "Wi-Fi 접속 정보",
        wifiSub: "Free High-Speed Wi-Fi",
        lblSsid5G: "SSID (5GHz - 고속)",
        lblSsid24G: "SSID (2.4GHz)",
        lblWifiPassword: "Wi-Fi 비밀번호",
        btnCopy: "복사",

        rulesTitle: "하우스 룰 (숙박 규칙)",
        rulesSub: "Important House Rules",
        rulePenaltyTitle: "위약금 규정 (30,000엔):",
        rulePenaltyDesc: "이웃 배려를 위해 규정 위반이나 소음 민원 발생 시 위약금 청구 및 즉시 퇴실 조치됩니다.",
        rule1Title: "전구역 금연",
        rule1Desc: "실내, 발코니, 건물 공용부 전체 금연(전자담배 포함)입니다.",
        rule2Title: "20:00 이후 소음 엄금",
        rule2Desc: "야간에는 정숙 시간입니다. 파티 금지. 창문을 닫고 TV 및 대화 소리를 줄여주세요.",
        rule3Title: "신발 벗기",
        rule3Desc: "일본 문화에 따라 현관에서 반드시 신발을 벗고 들어오세요.",
        rule4Title: "미등록자 입실 불가",
        rule4Desc: "예약 인원 외의 방문객 입실 및 무단 숙박은 엄격히 금지됩니다.",

        nearbyTitle: "주변 검색 & 주차장 지도",
        nearbySub: "Neighborhood & Parking Guide",
        btnGoogleMyMap: "주변 추천 지도 열기 (Google My Maps)",
        placeParkTitle: "인근 유료 주차장",
        placeParkTag: "전용 주차장 없음·도로 주차 불가",
        placeParkDesc: "차량으로 오실 경우 주변의 유료 주차장을 이용해 주세요.",
        btnSearchPark: "가까운 주차장 찾기",
        placeSuperTitle: "슈퍼마켓 '코노미야'",
        placeSuperTag: "식료품·생필품",
        placeSuperDesc: "신선한 식재료와 현지 식품을 구매할 수 있는 슈퍼마켓입니다. (도보 몇 분)",
        btnSearchSuper: "경로 보기",
        placeStoreTitle: "편의점 '로손'",
        placeStoreTag: "24시간 영업·ATM",
        placeStoreDesc: "심야 쇼핑 및 ATM 현금 인출에 편리합니다. (도보 바로 앞)",
        btnSearchStore: "경로 보기",
        placeFoodTitle: "현지 먹거리",
        placeFoodTag: "타코야끼·오코노미야끼",
        placeFoodDesc: "상가 주변에 오사카 소울푸드 맛집이 모여 있습니다. (20시 영업종료 다수)",
        btnSearchFood: "음식점 찾기",

        cultureTitle: "🇯🇵 일본 여행 매너 & 에티켓",
        cultureSub: "Japan Travel Etiquette Tips",
        cul1Title: "현관에서 신발 벗기",
        cul1Desc: "현관에서 신발을 벗는 것이 일본 문화입니다. 실내에서는 슬리퍼나 맨발로 지내주세요.",
        cul2Title: "팁 문화 없음",
        cul2Desc: "일본의 식당이나 택시에서는 팁을 주지 않습니다. 표기된 금액만 지불하세요.",
        cul3Title: "오사카 에스컬레이터",
        cul3Desc: "오사카에서 에스컬레이터를 탈 때는 【오른쪽】에 서서 왼쪽을 비워둡니다.",

        checkoutTitle: "체크아웃 절차",
        checkoutSub: "Check-out Checklist",
        checkoutTimeTitle: "체크아웃 시간: 오전 10:00 까지",
        checkoutTimeDesc: "청소 준비를 위해 체크아웃 시간을 엄수해 주시기 바랍니다.",
        checkoutListTitle: "📋 퇴실 전 체크리스트",
        coStep1: "소지품 확인: 충전기, 옷, 세면도구. ※TV (Netflix 등) 로그아웃 필수.",
        coStep2: "전원/에어컨 끄기: 전등, 에어컨, 보일러를 끄고 모든 창문을 잠가주세요.",
        coStep3: "태블릿 조작: 거실 태블릿에서 '체크아웃' 조작을 완료해 주세요.",
        coStep4: "쓰레기 처리: 외부에 버리지 마시고 실내 쓰레기통에 모아두세요.",
        coStep5: "문 잠금 & 열쇠 반납: 현관문을 잠그고 키박스에 열쇠를 넣은 후 번호를 흩뜨려 주세요.",

        faqTitle: "FAQ & 고객 지원",
        faqSub: "Troubleshooting & Support",
        btnChatbot: "24시간 챗봇 열기",
        faq1Q: "Q. 연박 중 쓰레기가 쌓이면 어떻게 하나요?",
        faq1A: "봉투에 모아 【건물 앞 전용 쓰레기 수거함】에 버려주세요 (일요일 제외).",
        faq2Q: "Q. 키박스가 열리지 않습니다",
        faq2A: "메시지로 받으신 비밀번호를 중앙에 맞추고 커버를 열어주세요.",
        faq3Q: "Q. 20:00 이후 늦은 도착 시?",
        faq3A: "24시간 셀프 체크인이 가능합니다. 야간 소음에 주의해 주세요.",

        sosTitle: "🆘 긴급 연락처 & 다국어 헬프데스크",

        taxiModalTitle: "🚖 택시 기사님에게 보여주는 화면",
        taxiModalDesc: "기사님에게 이 일본어 주소 화면을 보여주세요.",
        taxiModalNote: "*도로가 좁으니 근처에서 하차하시는 것을 추천합니다.",
        btnCopyAddress: "일본어 주소 복사하기"
      },

      zh: {
        navHome: "首页·概要",
        navAccess: "交通路线",
        navCheckin: "入住指南",
        navWifi: "Wi-Fi与设备",
        navRules: "房屋守则",
        navNearby: "周边搜索地图",
        navCheckout: "退房流程",
        navFaq: "常见问题与救助",

        heroBadge: "住宿指南 Web Portal",
        heroTitle: "欢迎来到 フォルモント住之江 101号室！",
        heroDesc: "祝您在大阪度过愉快的时光！本网站为您提供地址指引、钥匙领取、平板入住、Wi-Fi及周边地图等全套信息。",

        quickTaxi: "出租车用卡",
        quickWifi: "Wi-Fi密码",
        quickCheckin: "钥匙与入住",
        quickHelp: "求助与FAQ",

        smartCheckinTitle: "💡【强烈推荐】预先登记（Smart Check-in）",
        smartCheckinSub: "大幅缩短入住当天在房间平板上的输入时间",
        smartCheckinDesc: "根据日本法律规定，所有住客均需登记身份信息。请在到达前通过预订消息中的链接完成线上预先登记。",

        accessTitle: "交通路线与交通指南",
        accessSub: "Address & Transport Guide",
        lblAddress: "📍 详细地址",
        btnOpenMap: "打开Google地图",
        btnPhotoGuide: "图文带路指南",
        lblTrain: "🚃 最近车站与关西机场路线",
        kixRouteTitle: "关西国际机场 (KIX) 出发路线:",
        kixRouteDesc: "乘坐南海电车特急Rapi:t或空港急行至“天下茶屋站”，换乘南海本线慢车（各站停车），在“粉浜站”或“住吉大社站”下车。",
        lblTransitGuide: "⏱ 前往主要景点预估时间",
        carWarnTitle: "自驾住客请注意（重要）:",
        carWarnDesc: "本设施无专用停车场，且门前道路极窄禁止违章停车。请务必使用附近的收费停车场。",

        checkinTitle: "入住与钥匙领取流程",
        checkinSub: "Self Check-in Process",
        step1Title: "1. 到达并从密码盒中取出钥匙",
        step1Desc: "请在建筑物外的钥匙盒上拨对密码，取出房间钥匙。",
        lblKeyCode: "钥匙盒密码",
        btnCheckinGuide: "钥匙盒位置图文指南",
        step2Title: "2. 用钥匙开门入室",
        step2Desc: "使用钥匙打开101号室。请务必在玄关处脱鞋。",
        lockWarnTitle: "注意：非自动锁",
        lockWarnDesc: "外出及退房时，请务必使用钥匙手动锁门。",
        step3Title: "3.【必须】使用客厅平板登记",
        step3Desc: "进入房间后请首先在客厅平板（maneKEY）上完成全员护照及身份登记。",
        step3Tip: "※已预先登记的住客只需将二维码对准摄像头即可快速完成。",

        wifiTitle: "Wi-Fi 连接信息",
        wifiSub: "Free High-Speed Wi-Fi",
        lblSsid5G: "SSID (5GHz - 高速)",
        lblSsid24G: "SSID (2.4GHz)",
        lblWifiPassword: "Wi-Fi 密码",
        btnCopy: "复制",

        rulesTitle: "房屋守则 (House Rules)",
        rulesSub: "Important House Rules",
        rulePenaltyTitle: "违约金规定（30,000日元）:",
        rulePenaltyDesc: "为避免影响邻居，若发生违规或噪音投诉，将收取违约金并要求立即退房。",
        rule1Title: "全面禁烟",
        rule1Desc: "室内、阳台及楼宇公共区域全禁烟（含电子烟）。",
        rule2Title: "20:00后 保持安静",
        rule2Desc: "严禁派对。夜间请关窗并调低电视和说话音量。",
        rule3Title: "严禁脱鞋进屋",
        rule3Desc: "请遵循日本习惯，在玄关脱鞋后进入室内。",
        rule4Title: "禁止未登记人员入内",
        rule4Desc: "严禁非预订人数之外的访客进入或住宿。",

        nearbyTitle: "周边搜索与停车场",
        nearbySub: "Neighborhood & Parking Guide",
        btnGoogleMyMap: "打开推荐周边地图 (Google My Maps)",
        placeParkTitle: "附近收费停车场",
        placeParkTag: "无专用停车场·禁止路边停车",
        placeParkDesc: "自驾前往时，请利用附近的付费计时停车场。",
        btnSearchPark: "查找附近停车场",
        placeSuperTitle: "Konomi-ya 超市",
        placeSuperTag: "生鲜·食品·日用品",
        placeSuperDesc: "方便采购新鲜食品与当地特色商品的超市（步行数分钟）。",
        btnSearchSuper: "查看路线",
        placeStoreTitle: "罗森便利店 (Lawson)",
        placeStoreTag: "24小时营业·ATM",
        placeStoreDesc: "深夜购物及取款非常方便（步行即达）。",
        btnSearchStore: "查看路线",
        placeFoodTitle: "当地特色美食",
        placeFoodTag: "章鱼烧·御好烧",
        placeFoodDesc: "商店街周边汇集大阪地道美食店（大多20:00打烊）。",
        btnSearchFood: "查找附近美食",

        cultureTitle: "🇯🇵 日本旅行礼仪与小常识",
        cultureSub: "Japan Travel Etiquette Tips",
        cul1Title: "玄关脱鞋",
        cul1Desc: "进屋在玄关脱鞋是日本的传统文化，室内请穿拖鞋或赤脚。",
        cul2Title: "无需付小费",
        cul2Desc: "日本的餐厅和出租车没有给小费的习惯，只支付账单金额即可。",
        cul3Title: "大阪扶梯习惯",
        cul3Desc: "在大阪乘坐自动扶梯时，请站在【右侧】，空出左侧供急行人员通过。",

        checkoutTitle: "退房流程与清单",
        checkoutSub: "Check-out Checklist",
        checkoutTimeTitle: "退房时间: 10:00 AM 前",
        checkoutTimeDesc: "请严格遵守退房时间，以便清洁人员准时整理房间。",
        checkoutListTitle: "📋 退房前检查清单",
        coStep1: "遗留物品: 检查充电器、衣物，并退出电视上的Netflix等账号。",
        coStep2: "关闭电源: 关闭电灯、空调、热水器并锁好所有窗户。",
        coStep3: "平板操作: 在客厅平板上点击“退房(Check-out)”。",
        coStep4: "垃圾处理: 无需拿到室外，归拢在室内垃圾桶即可（清洁员会处理）。",
        coStep5: "锁门与还钥匙: 锁好房门，将钥匙放回室外密码盒并打乱密码。",

        faqTitle: "常见问题与救助",
        faqSub: "Troubleshooting & Support",
        btnChatbot: "打开24小时客服机器人",
        faq1Q: "Q. 连续入住期间垃圾满了怎么办？",
        faq1A: "装袋后放至【楼前的专属垃圾箱】（周日不回收，请勿在周日丢弃）。",
        faq2Q: "Q. 钥匙盒无法打开怎么办？",
        faq2A: "将密码【5758】对准中间，直接拉开盒盖即可。",
        faq3Q: "Q. 20:00以后晚到怎么办？",
        faq3A: "支持24小时自助入住。深夜请注意轻拿行李，避免发出噪音。",

        sosTitle: "🆘 紧急求助与多语言热线",

        taxiModalTitle: "🚖 出租车司机展示画面",
        taxiModalDesc: "请将此画面出示给司机看。",
        taxiModalNote: "*门前道路狭窄，建议让司机在附近方便处停车。",
        btnCopyAddress: "复制日文地址"
      },

      ko: {
        navHome: "홈·개요",
        navAccess: "오시는 길",
        navCheckin: "체크인 방법",
        navWifi: "Wi-Fi & 시설",
        navRules: "하우스 룰",
        navNearby: "주변 검색 지도",
        navCheckout: "체크아웃",
        navFaq: "FAQ & 긴급 도움",

        heroBadge: "게스트 포털 Web 가이드",
        heroTitle: "フォルモント住之江 101에 오신 것을 환영합니다!",
        heroDesc: "편안한 오사카 여행을 즐겨보세요! 위치, 열쇠 해제, 패드 체크인, Wi-Fi 정보, 주변 지도를 안내해 드립니다.",

        quickTaxi: "택시 화면",
        quickWifi: "Wi-Fi 정보",
        quickCheckin: "열쇠 & 체크인",
        quickHelp: "자주 묻는 질문",

        smartCheckinTitle: "💡 [강력 추천] 사전 등록 (스마트 체크인)",
        smartCheckinSub: "당일 객실 태블릿 입력 시간을 크게 단축할 수 있습니다",
        smartCheckinDesc: "일본 법령에 따라 모든 숙박객의 정보 등록이 의무화되어 있습니다. 메시지의 링크를 통해 사전에 입력을 완료해 주세요.",

        accessTitle: "오시는 길 & 교통 가이드",
        accessSub: "Address & Transport Guide",
        lblAddress: "📍 숙소 주소",
        btnOpenMap: "Google 지도 열기",
        btnPhotoGuide: "사진 길안내 가이드",
        lblTrain: "🚃 가까운 역 & 간사이 공항에서 오시는 길",
        kixRouteTitle: "간사이 국제공항(KIX) 출발:",
        kixRouteDesc: "난카이 전철 '라피트' 또는 '공항급행'을 타고 '덴가차야역'으로 이동 후, 난카이 본선 보통열차로 환승하여 '코하마역' 또는 '스미요시타이샤역'에서 하차하세요.",
        lblTransitGuide: "⏱ 주요 관광지 소요 시간",
        carWarnTitle: "차량 이용 게스트 주의사항 (중요):",
        carWarnDesc: "전용 주차장이 없으며 건물 앞 도로는 주정차 금지구역입니다. 반드시 근처의 동전 주차장을 이용해 주세요.",

        checkinTitle: "체크인 & 열쇠 수령 방법",
        checkinSub: "Self Check-in Process",
        step1Title: "1. 도착 및 키박스에서 열쇠 꺼내기",
        step1Desc: "건물 밖에 설치된 키박스의 비밀번호를 맞추고 열쇠를 꺼내세요.",
        lblKeyCode: "키박스 비밀번호",
        btnCheckinGuide: "키박스 위치 사진 가이드",
        step2Title: "2. 열쇠로 문을 열고 입실하기",
        step2Desc: "열쇠로 101호 문을 열고 들어오세요. 현관에서 신발을 벗어주세요.",
        lockWarnTitle: "주의: 오토락이 아닙니다",
        lockWarnDesc: "외출 및 퇴실 시에는 반드시 열쇠로 수동 잠금을 해주세요.",
        step3Title: "3. [필수] 거실 태블릿에서 등록 절차",
        step3Desc: "입실 후 가장 먼저 거실에 비치된 태블릿(maneKEY)으로 모든 숙박객의 등록을 완료해 주세요.",
        step3Tip: "*사전 등록을 완료하신 분은 화면의 QR코드를 카메라에 대기만 하면 됩니다.",

        wifiTitle: "Wi-Fi 접속 정보",
        wifiSub: "Free High-Speed Wi-Fi",
        lblSsid5G: "SSID (5GHz - 고속)",
        lblSsid24G: "SSID (2.4GHz)",
        lblWifiPassword: "Wi-Fi 비밀번호",
        btnCopy: "복사",

        rulesTitle: "하우스 룰 (숙박 규칙)",
        rulesSub: "Important House Rules",
        rulePenaltyTitle: "위약금 규정 (30,000엔):",
        rulePenaltyDesc: "이웃 배려를 위해 규정 위반이나 소음 민원 발생 시 위약금 청구 및 즉시 퇴실 조치됩니다.",
        rule1Title: "전구역 금연",
        rule1Desc: "실내, 발코니, 건물 공용부 전체 금연(전자담배 포함)입니다.",
        rule2Title: "20:00 이후 소음 엄금",
        rule2Desc: "야간에는 정숙 시간입니다. 파티 금지. 창문을 닫고 TV 및 대화 소리를 줄여주세요.",
        rule3Title: "신발 벗기",
        rule3Desc: "일본 문화에 따라 현관에서 반드시 신발을 벗고 들어오세요.",
        rule4Title: "미등록자 입실 불가",
        rule4Desc: "예약 인원 외의 방문객 입실 및 무단 숙박은 엄격히 금지됩니다.",

        nearbyTitle: "주변 검색 & 주차장 지도",
        nearbySub: "Neighborhood & Parking Guide",
        btnGoogleMyMap: "주변 추천 지도 열기 (Google My Maps)",
        placeParkTitle: "인근 유료 주차장",
        placeParkTag: "전용 주차장 없음·도로 주차 불가",
        placeParkDesc: "차량으로 오실 경우 주변의 유료 주차장을 이용해 주세요.",
        btnSearchPark: "가까운 주차장 찾기",
        placeSuperTitle: "슈퍼마켓 '코노미야'",
        placeSuperTag: "식료품·생필품",
        placeSuperDesc: "신선한 식재료와 현지 식품을 구매할 수 있는 슈퍼마켓입니다. (도보 몇 분)",
        btnSearchSuper: "경로 보기",
        placeStoreTitle: "편의점 '로손'",
        placeStoreTag: "24시간 영업·ATM",
        placeStoreDesc: "심야 쇼핑 및 ATM 현금 인출에 편리합니다. (도보 바로 앞)",
        btnSearchStore: "경로 보기",
        placeFoodTitle: "현지 먹거리",
        placeFoodTag: "타코야끼·오코노미야끼",
        placeFoodDesc: "상가 주변에 오사카 소울푸드 맛집이 모여 있습니다. (20시 영업종료 다수)",
        btnSearchFood: "음식점 찾기",

        cultureTitle: "🇯🇵 일본 여행 매너 & 에티켓",
        cultureSub: "Japan Travel Etiquette Tips",
        cul1Title: "현관에서 신발 벗기",
        cul1Desc: "현관에서 신발을 벗는 것이 일본 문화입니다. 실내에서는 슬리퍼나 맨발로 지내주세요.",
        cul2Title: "팁 문화 없음",
        cul2Desc: "일본의 식당이나 택시에서는 팁을 주지 않습니다. 표기된 금액만 지불하세요.",
        cul3Title: "오사카 에스컬레이터",
        cul3Desc: "오사카에서 에스컬레이터를 탈 때는 【오른쪽】에 서서 왼쪽을 비워둡니다.",

        checkoutTitle: "체크아웃 절차",
        checkoutSub: "Check-out Checklist",
        checkoutTimeTitle: "체크아웃 시간: 오전 10:00 까지",
        checkoutTimeDesc: "청소 준비를 위해 체크아웃 시간을 엄수해 주시기 바랍니다.",
        checkoutListTitle: "📋 퇴실 전 체크리스트",
        coStep1: "소지품 확인: 충전기, 옷, 세면도구. ※TV (Netflix 등) 로그아웃 필수.",
        coStep2: "전원/에어컨 끄기: 전등, 에어컨, 보일러를 끄고 모든 창문을 잠가주세요.",
        coStep3: "태블릿 조작: 거실 태블릿에서 '체크아웃' 조작을 완료해 주세요.",
        coStep4: "쓰레기 처리: 외부에 버리지 마시고 실내 쓰레기통에 모아두세요.",
        coStep5: "문 잠금 & 열쇠 반납: 현관문을 잠그고 키박스에 열쇠를 넣은 후 번호를 흩뜨려 주세요.",

        faqTitle: "FAQ & 고객 지원",
        faqSub: "Troubleshooting & Support",
        btnChatbot: "24시간 챗봇 열기",
        faq1Q: "Q. 연박 중 쓰레기가 쌓이면 어떻게 하나요?",
        faq1A: "봉투에 모아 【건물 앞 전용 쓰레기 수거함】에 버려주세요 (일요일 제외).",
        faq2Q: "Q. 키박스가 열리지 않습니다",
        faq2A: "비밀번호 【5758】을 중앙에 맞추고 커버를 열어주세요.",
        faq3Q: "Q. 20:00 이후 늦은 도착 시?",
        faq3A: "24시간 셀프 체크인이 가능합니다. 야간 소음에 주의해 주세요.",

        sosTitle: "🆘 긴급 연락처 & 다국어 헬프데스크",

        taxiModalTitle: "🚖 택시 기사님에게 보여주는 화면",
        taxiModalDesc: "기사님에게 이 일본어 주소 화면을 보여주세요.",
        taxiModalNote: "*도로가 좁으니 근처에서 하차하시는 것을 추천합니다.",
        btnCopyAddress: "일본어 주소 복사하기"
      }
    };

    let currentLang = 'ja';

    
module.exports = i18nData;