
    const i18nData = {
  "ja": {
    "navHome": "トップ・概要",
    "navAccess": "アクセス・移動",
    "navCheckin": "チェックイン方法",
    "navWifi": "Wi-Fi & 設備",
    "navRules": "ハウスルール",
    "navNearby": "周辺検索・マップ",
    "navCheckout": "チェックアウト",
    "navFaq": "FAQ & 緊急ヘルプ",
    "heroBadge": "大阪・住之江公園エリア",
    "heroTitle": "フォルモント住之江 101 へようこそ！",
    "heroSub": "ご滞在を快適にお過ごしいただくためのポータルサイトです",
    "quickTaxi": "タクシー画面",
    "quickWifi": "Wi-Fi 情報",
    "quickCheckin": "入室方法",
    "quickHelp": "緊急連絡先",
    "cardAddressTitle": "所在地 & アクセス概要",
    "cardAddressDesc": "〒559-0001 大阪府大阪市住之江区住之江 3-7-20 フォルモント住之江 101",
    "btnCopyAddress": "住所をコピー",
    "btnOpenMap": "Google マップで見る",
    "btnTaxiCard": "タクシー運転手に見せる画面を表示",
    "smartCheckinTitle": "スマートチェックインのご案内（事前登録）",
    "smartCheckinSub": "当日の部屋タブレットの入力時間を大幅短縮できます",
    "smartCheckinDesc": "日本の法令により全宿泊者の情報登録が必要です。事前メッセージに添付されている「スマートチェックイン案内URL / QRコード」より、ご自宅や移動中に事前入力をお済ませいただくと、当日スムーズに入室いただけます。",
    "accessTitle": "施設へのアクセス & 移動方法",
    "accessSub": "最寄り駅および主要スポット・空港からのアクセス",
    "lblAddress": "📍 所在地",
    "btnPhotoGuide": "写真付き道順ガイドを見る",
    "lblTrain": "🚃 最寄り駅＆関西空港からのアクセス",
    "kixRouteTitle": "関西国際空港（KIX）からのルート:",
    "kixRouteDesc": "南海電鉄「ラピート」または「空港急行」で「天下茶屋（てんがちゃや）駅」下車、南海本線に乗り換えて「住ノ江（すみのえ）駅」下車（徒歩約7分）。",
    "lblTransitGuide": "⏱ 主要スポットへの所要時間目安",
    "carWarnTitle": "お車でお越しの方へ（重要）:",
    "carWarnDesc": "当施設には専用駐車場がございません。また前面道路は非常に狭く駐停車厳禁です。お車でお越しの際は必ず近隣のコインパーキングをご利用ください。",
    "checkinTitle": "チェックイン & 入室手順",
    "checkinSub": "セルフチェックインの流れ",
    "step1Title": "1. 到着・キーボックスから鍵を取り出す",
    "step1Desc": "建物外に設置されたキーボックスのダイヤルを合わせ、お部屋の鍵を取り出してください。",
    "lblKeyCode": "🔑 キーボックスの暗証番号について",
    "lblKeyNotice": "ご宿泊日が近づきましたら、別途メッセージにて暗証番号をお送りいたします。届いたメッセージをご確認ください。",
    "btnCheckinGuide": "キーボックス設置場所写真ガイド",
    "step2Title": "2. お部屋の鍵を開けて入室する",
    "step2Desc": "鍵を使って101号室のドアを開けてお入りください。玄関で必ず靴を脱いで上がってください。",
    "lockWarnTitle": "オートロックではありません:",
    "lockWarnDesc": "外出時および退室時は、必ず手動で鍵をかけて施錠してください。",
    "step3Title": "3. 【必須】リビングのタブレットで登録手続き",
    "step3Desc": "部屋に入られたら一番最初に、リビングの専用タブレット（maneKEY）にてチェックイン・本人確認手続きを行ってください。",
    "step3Tip": "※事前登録済みの方は、画面のQRコードをカメラにかざすだけでスムーズに完了できます。",
    "wifiTitle": "Wi-Fi 接続情報 & 設備",
    "wifiSub": "無料高速Wi-Fiおよび家電の利用方法",
    "lblSsid5G": "SSID (5GHz - 高速)",
    "btnCopy": "コピー",
    "lblSsid24G": "SSID (2.4GHz)",
    "lblWifiPassword": "Wi-Fi パスワード",
    "rulesTitle": "ハウスルール (ご滞在のルール)",
    "rulesSub": "快適なご滞在のために必ずお守りください",
    "rulePenaltyTitle": "違約金規定（30,000円）:",
    "rulePenaltyDesc": "近隣住民の方への配慮のため、規約違反や騒音クレームが発生した場合は違約金の請求および即刻退室となります。",
    "rule1Title": "完全禁煙",
    "rule1Desc": "室内、バルコニー、敷地内・共用部はすべて禁煙（電子タバコ含む）です。",
    "rule2Title": "20:00以降 騒音厳禁",
    "rule2Desc": "夜間は静穏時間です。パーティー禁止。窓を閉め、テレビや会話の音量にご配慮ください。",
    "rule3Title": "土足厳禁",
    "rule3Desc": "日本の習慣に従い、必ず玄関で靴を脱いでお部屋へお上がりください。",
    "rule4Title": "未登録者の入室不可",
    "rule4Desc": "ご予約人数以外のゲストの無断入室・宿泊は固く禁止しております。",
    "nearbyTitle": "周辺スポット検索 & 駐車場マップ",
    "nearbySub": "近隣のスーパー・コンビニ・飲食店案内",
    "btnGoogleMyMap": "周辺エリアおすすめマップを開く (Google My Maps)",
    "placeParkTitle": "近隣コインパーキング",
    "placeParkTag": "専用駐車場なし・路上駐車不可",
    "placeParkDesc": "車でお越しの際は、周辺の有料コインパーキングをご利用ください。",
    "btnSearchPark": "近くの駐車場を探す",
    "placeSuperTitle": "スーパー「KINSHO（近商ストア）」",
    "placeSuperTag": "食料品・日用品",
    "placeSuperDesc": "最寄りの便利なスーパーマーケット「近商ストア」。新鮮な食料品やお惣菜が揃っています。（徒歩すぐ）",
    "btnSearchSuper": "ルートを見る",
    "placeStoreTitle": "コンビニ「ローソン」",
    "placeStoreTag": "24時間営業・ATM",
    "placeStoreDesc": "深夜の買い物やATMでの現金引き出しに便利です。（徒歩すぐ）",
    "btnSearchStore": "ルートを見る",
    "placeFoodTitle": "洋食・ローカルグルメ「弥六（やろく）」",
    "placeFoodTag": "洋食・名物ヒレカツ",
    "placeFoodDesc": "地元で大人気の老舗洋食店「弥六」。名物のヒレカツやオムライスが絶品です。（粉浜商店街エリア）",
    "btnSearchFood": "「弥六」の地図・詳細を見る ↗",
    "placeTakoTitle": "たこ焼き・粉もの「キャベツハウス」",
    "placeTakoTag": "たこ焼き・大阪名物",
    "placeTakoDesc": "粉浜商店街にある地元で人気のたこ焼き店。焼きたてアツアツの大阪名物たこ焼きが楽しめます。（徒歩圏内）",
    "btnSearchTako": "「たこ焼き店」の地図を見る ↗",
    "cultureTitle": "🇯🇵 日本滞在マナー & ミニガイド",
    "cultureSub": "知っておくと便利なマナーガイド",
    "cul1Title": "靴を脱ぐ習慣",
    "cul1Desc": "玄関で靴を脱ぐのが日本の文化です。お部屋の中はスリッパまたは素足でお過ごしください。",
    "cul2Title": "チップ不要",
    "cul2Desc": "日本のレストランやタクシーではチップの習慣がありません。表示料金のみお支払いください。",
    "cul3Title": "大阪のエスカレーター",
    "cul3Desc": "大阪ではエスカレーターに乗る際、右側に立ち、左側を空けるのが一般的です。",
    "checkoutTitle": "チェックアウト手順",
    "checkoutSub": "ご退室時の確認事項",
    "checkoutTimeTitle": "チェックアウト時間: 10:00 AM まで",
    "checkoutTimeDesc": "清掃スタッフの準備のため、お時間厳守でのご出発をお願いいたします。",
    "checkoutListTitle": "📋 退出時チェックリスト",
    "coStep1": "お忘れ物確認: 充電器、衣類、テレビの動画サービスログアウトをご確認ください。",
    "coStep2": "電源・エアコンオフ: 全ての照明、エアコン、暖房を消し、窓の鍵をかけてください。",
    "coStep3": "タブレット操作: リビングのタブレットで「チェックアウト」完了ボタンを押してください。",
    "coStep4": "ゴミの処理: まとめられたゴミは室内の中に置いてご退室ください。",
    "coStep5": "施錠 & 鍵の返却: ドアを鍵で施錠し、鍵をキーボックスに戻してダイヤルを回してください。",
    "faqTitle": "FAQ (よくある質問) & サポート",
    "faqSub": "トラブル解決とサポート窓口",
    "btnChatbot": "24時間 サポートチャットボットを開く",
    "faq1Q": "Q. 滞在中のゴミが溜まった場合はどうすればいいですか？",
    "faq1A": "袋にまとめて【建物前の専用ゴミ収集箱】にお出しください。（※日曜日の回収はございませんので、日曜日の排出はお控えください。）<br>※ゴミの分別ルールや詳細については、<a href=\"https://mastor-prog.github.io/house-guide/#garbage\" target=\"_blank\" rel=\"noopener noreferrer\" style=\"color:var(--accent-gold); text-decoration:underline; font-weight:600;\">ハウスマニュアル「5. Garbage / ゴミの分別」 ↗</a> をご参照ください。",
    "faq2Q": "Q. 鍵が開かない・キーボックスの使い方がわからない",
    "faq2A": "メッセージでお送りした暗証番号を中央のラインに合わせ、そのまま手前にフタを開けてください（解錠レバーはありません）。",
    "faq3Q": "Q. 夜遅く（20:00以降）に到着する場合は？",
    "faq3A": "24時間セルフチェックインに対応しておりますので、遅い時間のご到着でも問題ございません。住宅街のため、近隣住民の皆様の睡眠の妨げにならないよう、屋外（建物周辺や道路）での会話はお控えいただき、スーツケースを持ち上げて運ぶなど静かな移動をお願いいたします。",
    "sosTitle": "🆘 緊急連絡先 & 多言語ヘルプデスク",
    "sosPolice": "警察: 110番",
    "sosFire": "救急・消防: 119番",
    "contactBtn": "24時間 サポートチャットボットを開く",
    "taxiModalTitle": "🚖 タクシー運転手に見せる画面",
    "taxiModalDesc": "タクシーをご利用の際は、この画面を運転手さんに見せて目的地をお伝えください。",
    "taxiModalNote": "*前面道路が狭いため、近くで降車することをお勧めいたします。",
    "btnCopyAddressModal": "日本語住所をコピー",
    "heroDesc": "ご滞在を快適にお過ごしいただくためのポータルサイトです",
    "navManual": "ハウスマニュアル ↗",
    "quickManual": "📖 ハウスマニュアル",
    "btnHouseManual": "Web版ハウスマニュアルを見る ↗",
    "catBefore": "🛫 ご到着前",
    "catStay": "🏠 ご滞在中",
    "catCheckout": "🚪 ご退室 & ヘルプ",
    "navManualCard": "📖 ハウスマニュアル",
    "manualTitle": "📖 WEB版 ハウスマニュアル (House Manual)",
    "manualTag": "家電・設備・分別",
    "manualDesc": "エアコンや洗濯機などの家電の使い方、お部屋の設備の操作方法、ゴミの分別ルールなど、快適なご滞在に必要なすべての情報を網羅した公式オンラインガイドです。",
    "btnOpenManual": "WEB版ハウスマニュアルを開く ↗",
    "checkoutManualNote": "※チェックアウト手順や写真付き詳細ガイドは、ハウスマニュアルをご参照ください。",
    "btnCheckoutManual": "📖 ハウスマニュアル「9. Check-out / チェックアウト」を見る ↗"
  },
  "en": {
    "navHome": "Home",
    "navAccess": "Access",
    "navCheckin": "Check-in",
    "navWifi": "Wi-Fi & Amenities",
    "navRules": "House Rules",
    "navNearby": "Map & Nearby",
    "navCheckout": "Check-out",
    "navFaq": "FAQ & Support",
    "heroBadge": "Suminoekoen Area, Osaka",
    "heroTitle": "Welcome to Vollmond Suminoe 101!",
    "heroSub": "Your guest portal guide for a comfortable stay",
    "quickTaxi": "Taxi Screen",
    "quickWifi": "Wi-Fi Info",
    "quickCheckin": "Check-in",
    "quickHelp": "Emergency",
    "cardAddressTitle": "Address & Map",
    "cardAddressDesc": "3-7-20 Suminoe, Suminoe-ku, Osaka-shi, Osaka 559-0001",
    "btnCopyAddress": "Copy Address",
    "btnOpenMap": "Open in Google Maps",
    "btnTaxiCard": "Show Taxi Screen to Driver",
    "smartCheckinTitle": "Pre-Check-in Guide (Online)",
    "smartCheckinSub": "Save time during check-in on the living room tablet",
    "smartCheckinDesc": "Japanese law requires guest registration. Please complete your registration via the pre-checkin URL/QR code sent in our message prior to arrival for a seamless check-in.",
    "accessTitle": "Access & Transportation Guide",
    "accessSub": "Directions from nearest station and Kansai Airport (KIX)",
    "lblAddress": "📍 Address",
    "btnPhotoGuide": "View Photo Directions Guide",
    "lblTrain": "🚃 Nearest Station & Access from Airport",
    "kixRouteTitle": "Route from Kansai International Airport (KIX):",
    "kixRouteDesc": "Take Nankai Express (Rapi:t or Airport Express) to Tengachaya Station, transfer to Nankai Main Line and get off at Suminoe Station (7 mins walk).",
    "lblTransitGuide": "⏱ Estimated Travel Time to Key Spots",
    "carWarnTitle": "Important Notice for Drivers:",
    "carWarnDesc": "No private parking available. Stopping/parking in front of the building is strictly prohibited. Please use nearby paid coin parking.",
    "checkinTitle": "Check-in & Room Key Retrieval",
    "checkinSub": "Self Check-in Process",
    "step1Title": "1. Arrival & Key Box Retrieval",
    "step1Desc": "Set the passcode on the lockbox outside the building and retrieve the room key.",
    "lblKeyCode": "🔑 Key Lockbox Passcode Notice",
    "lblKeyNotice": "The lockbox passcode will be sent to you via message prior to your check-in date.",
    "btnCheckinGuide": "Lockbox Photo Guide",
    "step2Title": "2. Unlock Room Door & Enter",
    "step2Desc": "Use key to unlock Room 101. Please remove your shoes at the entryway.",
    "lockWarnTitle": "NOT Auto-locking:",
    "lockWarnDesc": "Please manually lock the door with the key whenever you leave.",
    "step3Title": "3. [REQUIRED] Tablet Registration in Living Room",
    "step3Desc": "Immediately after entering, complete check-in & passport verification on the living room tablet (maneKEY).",
    "step3Tip": "※Pre-registered guests can simply scan the QR code on screen to complete quickly.",
    "wifiTitle": "Wi-Fi & Appliances Guide",
    "wifiSub": "Free High-Speed Wi-Fi & Amenities",
    "lblSsid5G": "SSID (5GHz - Fast)",
    "btnCopy": "Copy",
    "lblSsid24G": "SSID (2.4GHz)",
    "lblWifiPassword": "Wi-Fi Password",
    "rulesTitle": "House Rules",
    "rulesSub": "Important Rules for Your Stay",
    "rulePenaltyTitle": "Penalty Fee (30,000 JPY):",
    "rulePenaltyDesc": "Violations or noise complaints from neighbors will result in a 30,000 JPY fee & immediate eviction.",
    "rule1Title": "Strictly No Smoking",
    "rule1Desc": "Smoking (including e-cigarettes) is prohibited in rooms, balcony, and all building premises.",
    "rule2Title": "Quiet Hours after 20:00",
    "rule2Desc": "No parties. Keep noise, TV, and talking volume low at night to respect neighbors.",
    "rule3Title": "Shoes Off Inside",
    "rule3Desc": "Please take off shoes at the entrance as per Japanese custom.",
    "rule4Title": "Registered Guests Only",
    "rule4Desc": "Unregistered visitors are strictly forbidden from entering or staying.",
    "nearbyTitle": "Nearby Map & Search",
    "nearbySub": "Neighborhood Supermarkets, Stores & Restaurants",
    "btnGoogleMyMap": "Open Area Guide Map (Google My Maps)",
    "placeParkTitle": "Nearby Coin Parking",
    "placeParkTag": "No private parking / No street parking",
    "placeParkDesc": "Please use nearby paid coin parking spaces if traveling by car.",
    "btnSearchPark": "Find Nearby Parking",
    "placeSuperTitle": "Supermarket 'KINSHO'",
    "placeSuperTag": "Groceries & Daily Needs",
    "placeSuperDesc": "Nearest convenient supermarket 'KINSHO'. Offers fresh groceries and daily necessities (short walk).",
    "btnSearchSuper": "Get Route",
    "placeStoreTitle": "Convenience Store 'Lawson'",
    "placeStoreTag": "24h Open / ATM",
    "placeStoreDesc": "24h open store for drinks, snacks, and ATM cash withdrawal (short walk).",
    "btnSearchStore": "Get Route",
    "placeFoodTitle": "Local Dining 'Yaroku' (Western Food)",
    "placeFoodTag": "Famous Pork Cutlet & Omurice",
    "placeFoodDesc": "Famous long-established Western restaurant 'Yaroku' in Kohama, renowned for its tender pork cutlet.",
    "btnSearchFood": "Open 'Yaroku' on Maps ↗",
    "placeTakoTitle": "Takoyaki 'Cabbage House'",
    "placeTakoTag": "Takoyaki / Osaka Specialty",
    "placeTakoDesc": "Popular local Takoyaki spot in Kohama Shopping Street. Enjoy fresh and hot Osaka octopus balls! (Short walk)",
    "btnSearchTako": "Find Takoyaki Shops ↗",
    "cultureTitle": "🇯🇵 Japan Travel Tips & Etiquette",
    "cultureSub": "Useful Local Tips",
    "cul1Title": "Remove Shoes",
    "cul1Desc": "Remove shoes at entryway. Use slippers inside.",
    "cul2Title": "No Tipping",
    "cul2Desc": "Tipping is not practiced in Japan. Pay only listed prices.",
    "cul3Title": "Escalator Manners in Osaka",
    "cul3Desc": "Stand on the RIGHT side of escalators in Osaka, leaving left side open.",
    "checkoutTitle": "Check-out Process",
    "checkoutSub": "Check-out Checklist",
    "checkoutTimeTitle": "Check-out Time: By 10:00 AM",
    "checkoutTimeDesc": "Please leave on time so cleaning staff can prepare for next guests.",
    "checkoutListTitle": "📋 Check-out Checklist",
    "coStep1": "Belongings: Check phone chargers, clothes, and log out of Netflix on TV.",
    "coStep2": "Power off: Turn off all lights, AC, heaters, and lock all windows.",
    "coStep3": "Tablet: Complete 'Check-out' on the living room tablet.",
    "coStep4": "Trash: Leave gathered trash inside the room (do not put outside).",
    "coStep5": "Lock & Return Key: Lock front door, return key to lockbox and scramble dials.",
    "faqTitle": "FAQ & Support",
    "faqSub": "Troubleshooting & Support",
    "btnChatbot": "Open 24h Support Chatbot",
    "faq1Q": "Q. How to dispose trash during long stay?",
    "faq1A": "Put bagged trash into the dedicated box in front of the building (Except Sundays).<br>For sorting rules and details, please refer to <a href=\"https://mastor-prog.github.io/house-guide/#garbage\" target=\"_blank\" rel=\"noopener noreferrer\" style=\"color:var(--accent-gold); text-decoration:underline; font-weight:600;\">\"5. Garbage\" in the House Manual ↗</a>.",
    "faq2Q": "Q. Key lockbox doesn't open",
    "faq2A": "Align the passcode sent to you in message to the center and open the cover directly.",
    "faq3Q": "Q. Late arrival after 20:00?",
    "faq3A": "Self check-in is available 24 hours so late arrival is not a problem. As this is a residential area, please refrain from talking outside (around the building or street) so as not to disturb neighbors' sleep, and handle your luggage quietly.",
    "sosTitle": "🆘 Emergency Contacts",
    "sosPolice": "Police: 110",
    "sosFire": "Ambulance/Fire: 119",
    "contactBtn": "Open 24h Support Chatbot",
    "taxiModalTitle": "🚖 Screen for Taxi Driver",
    "taxiModalDesc": "Show this Japanese address screen to your driver.",
    "taxiModalNote": "*Street is narrow, ask driver to stop nearby.",
    "btnCopyAddressModal": "Copy Japanese Address",
    "heroDesc": "Your guest portal guide for a comfortable stay",
    "navManual": "House Manual ↗",
    "quickManual": "📖 House Manual",
    "btnHouseManual": "View Web House Manual ↗",
    "catBefore": "🛫 Before Arrival",
    "catStay": "🏠 During Stay",
    "catCheckout": "🚪 Check-out & Support",
    "navManualCard": "📖 House Manual",
    "manualTitle": "📖 WEB House Manual",
    "manualTag": "Appliances & Rules",
    "manualDesc": "Official online guide covering appliance instructions (AC, washer), room facility usage, and trash sorting rules.",
    "btnOpenManual": "Open House Manual ↗",
    "checkoutManualNote": "* For detailed photo guides on check-out procedures, please check the House Manual.",
    "btnCheckoutManual": "📖 View \"9. Check-out\" in House Manual ↗"
  },
  "zh": {
    "navHome": "首页·概要",
    "navAccess": "交通路线",
    "navCheckin": "入住指南",
    "navWifi": "Wi-Fi与设备",
    "navRules": "房屋守则",
    "navNearby": "周边与地图",
    "navCheckout": "退房流程",
    "navFaq": "常见问题",
    "heroBadge": "大阪·住之江公园区域",
    "heroTitle": "欢迎入住 Vollmond 住之江 101！",
    "heroSub": "为您提供舒适住宿体验的自助指南",
    "quickTaxi": "出租车画面",
    "quickWifi": "Wi-Fi信息",
    "quickCheckin": "入室指南",
    "quickHelp": "紧急求助",
    "cardAddressTitle": "地址与交通概要",
    "cardAddressDesc": "大阪府大阪市住之江区住之江 3-7-20 フォルモント住之江 101 (邮编 559-0001)",
    "btnCopyAddress": "复制日文地址",
    "btnOpenMap": "打开 Google 地图",
    "btnTaxiCard": "显示给出租车司机的地址画面",
    "smartCheckinTitle": "在线预先登记指南（智能入住）",
    "smartCheckinSub": "可大幅缩短入住当天在平板上的操作时间",
    "smartCheckinDesc": "根据日本法律规定，所有住宿人员均需登记信息。请在入住前通过消息中的链接/二维码完成信息预填，以便快速入住。",
    "accessTitle": "交通与到达指南",
    "accessSub": "从最近车站及关西机场（KIX）的路线",
    "lblAddress": "📍 详细地址",
    "btnPhotoGuide": "查看带图路线指南",
    "lblTrain": "🚃 最近车站与机场交通",
    "kixRouteTitle": "关西国际机场（KIX）出发:",
    "kixRouteDesc": "乘坐南海电车（Rapi:t特急或机场急行）至“天下茶屋站”，换乘南海本线至“住之江站”下车（步行约7分钟）。",
    "lblTransitGuide": "⏱ 前往主要景点估计所需时间",
    "carWarnTitle": "自驾住客请注意（重要）:",
    "carWarnDesc": "本设施无专用停车场，且门前道路极窄禁止违章停车。请务必使用附近的收费停车场。",
    "checkinTitle": "入住与钥匙领取步骤",
    "checkinSub": "自助入住流程",
    "step1Title": "1. 到达并从密码盒中取出钥匙",
    "step1Desc": "在建筑物外的密码盒上对准密码，取出房间钥匙。",
    "lblKeyCode": "🔑 钥匙盒密码说明",
    "lblKeyNotice": "临近入住日期时，我们将通过消息另行发送钥匙盒密码，请注意查收。",
    "btnCheckinGuide": "钥匙盒位置图文指南",
    "step2Title": "2. 开锁并进入房间",
    "step2Desc": "用钥匙打开101室房门。入户时请务必在玄关处脱鞋。",
    "lockWarnTitle": "注意：非自动锁",
    "lockWarnDesc": "外出及退房时，请务必使用钥匙手动锁门。",
    "step3Title": "3. 【必须】使用客厅平板登记信息",
    "step3Desc": "进入房间后，请首先在客厅专用平板（maneKEY）上办理入住和身份验证。",
    "step3Tip": "※预先完成登记的住客，只需在屏幕前扫描二维码即可快速完成。",
    "wifiTitle": "Wi-Fi 连接与设备指南",
    "wifiSub": "免费高速Wi-Fi与家电使用",
    "lblSsid5G": "SSID (5GHz - 高速)",
    "btnCopy": "复制",
    "lblSsid24G": "SSID (2.4GHz)",
    "lblWifiPassword": "Wi-Fi 密码",
    "rulesTitle": "房屋守则",
    "rulesSub": "为了您的舒适住宿，请务必遵守",
    "rulePenaltyTitle": "违约金规定（30,000日元）:",
    "rulePenaltyDesc": "为避免影响邻居，如发生违反守则或噪音投诉，将收取30,000日元违约金并要求立即退房。",
    "rule1Title": "全面禁烟",
    "rule1Desc": "室内、阳台、大楼内及公共区域全面禁烟（含电子烟）。",
    "rule2Title": "20:00后保持安静",
    "rule2Desc": "夜间为安静时间。严禁派对。请关好窗户，降低电视及交谈音量。",
    "rule3Title": "室内禁止穿鞋",
    "rule3Desc": "遵照日本习惯，入户请在玄关脱鞋，换穿拖鞋或赤脚。",
    "rule4Title": "严禁未登记人员入内",
    "rule4Desc": "严禁预订人数以外的访客擅自入内或住宿。",
    "nearbyTitle": "周边检索与停车场地图",
    "nearbySub": "周边超市、便利店与美食推荐",
    "btnGoogleMyMap": "打开推荐地图 (Google My Maps)",
    "placeParkTitle": "周边收费停车场",
    "placeParkTag": "无专用停车位·禁止路边停放",
    "placeParkDesc": "自驾前往时，请利用周边的收费停车场。",
    "btnSearchPark": "查找附近停车场",
    "placeSuperTitle": "超市 'KINSHO (近商超市)'",
    "placeSuperTag": "生鲜·食品·日用品",
    "placeSuperDesc": "最近的便利超市“KINSHO”。提供新鲜食材、熟食及日常用品（步行即到）。",
    "btnSearchSuper": "查看路线",
    "placeStoreTitle": "便利店 'Lawson'",
    "placeStoreTag": "24小时营业·ATM",
    "placeStoreDesc": "方便夜间购物及ATM取现（步行即到）。",
    "btnSearchStore": "查看路线",
    "placeFoodTitle": "地道西餐·老字号“弥六 (Yaroku)”",
    "placeFoodTag": "招牌炸猪排·蛋包饭",
    "placeFoodDesc": "创业多年的当地知名西餐厅“弥六”，招牌菲力炸猪排与蛋包饭深受喜爱。",
    "btnSearchFood": "在地图上查看“弥六” ↗",
    "placeTakoTitle": "章鱼烧“Cabbage House”",
    "placeTakoTag": "章鱼烧·大阪名产",
    "placeTakoDesc": "粉浜商店街当地极具人气的章鱼烧店。尽情品尝现做热气腾腾的大阪名产章鱼烧。（步行可达）",
    "btnSearchTako": "在地图上查看章鱼烧店 ↗",
    "cultureTitle": "🇯🇵 日本礼仪与旅行小贴士",
    "cultureSub": "实用文化指南",
    "cul1Title": "脱鞋习惯",
    "cul1Desc": "进门脱鞋是日本文化，室内请穿拖鞋或袜履。",
    "cul2Title": "无需小费",
    "cul2Desc": "日本的餐厅和出租车均没有给小费的习惯，支付标价即可。",
    "cul3Title": "大阪电梯礼仪",
    "cul3Desc": "在大阪乘坐自动扶梯时，通常靠右站立，空出左侧供急行者通过。",
    "checkoutTitle": "退房流程",
    "checkoutSub": "退房注意事项",
    "checkoutTimeTitle": "退房时间: 上午 10:00 前",
    "checkoutTimeDesc": "为便于保洁人员准备，请务必准时退房。",
    "checkoutListTitle": "📋 退房检查清单",
    "coStep1": "检查遗留物品: 请检查充电器、衣物，并退出电视上的账号。",
    "coStep2": "关闭电源: 请关闭所有照明、空调、暖气，并锁好所有窗户。",
    "coStep3": "平板操作: 请在客厅平板上点击“退房”完成按钮。",
    "coStep4": "垃圾处理: 将整理好的垃圾放在室内即可（请勿遗留在室外）。",
    "coStep5": "锁门并还钥匙: 用钥匙将房门锁好，将钥匙放回密码盒并拨乱密码。",
    "faqTitle": "常见问题与救助",
    "faqSub": "故障排查与客服支援",
    "btnChatbot": "打开24小时在线客服",
    "faq1Q": "Q. 连续入住期间垃圾满了怎么办？",
    "faq1A": "装袋后放至【楼前的专属垃圾箱】（周日不回收，请勿在周日丢弃）。<br>详细分类规则与说明请参考 <a href=\"https://mastor-prog.github.io/house-guide/#garbage\" target=\"_blank\" rel=\"noopener noreferrer\" style=\"color:var(--accent-gold); text-decoration:underline; font-weight:600;\">房屋手册“5. Garbage / 垃圾分类” ↗</a>。",
    "faq2Q": "Q. 钥匙盒无法打开怎么办？",
    "faq2A": "请将消息中收到的密码对准中间，直接拉开盒盖即可。",
    "faq3Q": "Q. 20:00以后晚到怎么办？",
    "faq3A": "支持24小时自助入住，深夜到达也没问题。由于位于住宅区，为避免影响邻居休息，请勿在户外（大楼周边及道路）交谈，并请轻拿轻放行李。",
    "sosTitle": "🆘 紧急联系方式与多语言求助",
    "sosPolice": "报警电话: 110",
    "sosFire": "急救·火警: 119",
    "contactBtn": "打开24小时在线客服",
    "taxiModalTitle": "🚖 给出租车司机看的地址画面",
    "taxiModalDesc": "乘坐出租车时，请向司机出示此日文地址画面。",
    "taxiModalNote": "*门前道路狭窄，建议在附近下车。",
    "btnCopyAddressModal": "复制日文地址",
    "heroDesc": "为您提供舒适住宿体验的自助指南",
    "navManual": "房屋手册 ↗",
    "quickManual": "📖 房屋手册",
    "btnHouseManual": "查看Web版房屋手册 ↗",
    "catBefore": "🛫 行前及到达",
    "catStay": "🏠 入住期间",
    "catCheckout": "🚪 退房与帮助",
    "navManualCard": "📖 房屋手册",
    "manualTitle": "📖 在线房屋手册 (House Manual)",
    "manualTag": "家电·设备·垃圾分类",
    "manualDesc": "涵盖空调、洗衣机等家电使用说明、房间设施操作以及垃圾分类规则的官方在线指南。",
    "btnOpenManual": "打开房屋手册 ↗",
    "checkoutManualNote": "※退房流程的图文详细说明，请参考房屋手册。",
    "btnCheckoutManual": "📖 查看房屋手册“9. Check-out / 退房” ↗"
  },
  "ko": {
    "navHome": "홈·개요",
    "navAccess": "오시는 길",
    "navCheckin": "체크인 방법",
    "navWifi": "Wi-Fi 및 비품",
    "navRules": "이용 수칙",
    "navNearby": "주변 지도",
    "navCheckout": "체크아웃",
    "navFaq": "자주 묻는 질문",
    "heroBadge": "오사카 스미노에코엔 지역",
    "heroTitle": "폴몬트 스미노에 101에 오신 것을 환영합니다!",
    "heroSub": "편안한 숙박을 위한 게스트 포털 가이드입니다",
    "quickTaxi": "택시 화면",
    "quickWifi": "Wi-Fi 정보",
    "quickCheckin": "입실 방법",
    "quickHelp": "긴급 연락처",
    "cardAddressTitle": "주소 및 위치 개요",
    "cardAddressDesc": "우편번호 559-0001 오사카부 오사카시 스미노에구 스미노에 3-7-20 폴몬트 스미노에 101",
    "btnCopyAddress": "주소 복사하기",
    "btnOpenMap": "Google 지도에서 보기",
    "btnTaxiCard": "택시 기사님용 주소 화면 보기",
    "smartCheckinTitle": "사전 체크인 안내 (온라인)",
    "smartCheckinSub": "체크인 당일 객실 태블릿 입력 시간을 대폭 줄일 수 있습니다",
    "smartCheckinDesc": "일본 법령에 따라 모든 투숙객의 정보 등록이 필요합니다. 도착 전 메시지로 안내해 드린 QR코드/URL을 통해 사전 등록을 완료하시면 당일 빠른 입실이 가능합니다.",
    "accessTitle": "오시는 길 & 교통 안내",
    "accessSub": "가까운 역 및 간사이 공항(KIX)에서의 오시는 길",
    "lblAddress": "📍 상세 주소",
    "btnPhotoGuide": "사진 포함 길안내 가이드 보기",
    "lblTrain": "🚃 인근 역 및 공항 교통편",
    "kixRouteTitle": "간사이 국제공항(KIX) 출발 경로:",
    "kixRouteDesc": "난카이 전철(라피트 또는 공항급행) 승차 후 '텐가차야역' 하차, 난카이 본선으로 환승하여 '스미노에역' 하차 (도보 약 7분).",
    "lblTransitGuide": "⏱ 주요 관광지 소요 시간",
    "carWarnTitle": "차량 이용 게스트 주의사항 (중요):",
    "carWarnDesc": "전용 주차장이 없으며 건물 앞 도로는 주정차 금지구역입니다. 차량 이용 시 반드시 근처의 동전 주차장을 이용해 주세요.",
    "checkinTitle": "체크인 & 열쇠 수령 방법",
    "checkinSub": "셀프 체크인 프로세스",
    "step1Title": "1. 도착 및 키박스에서 열쇠 꺼내기",
    "step1Desc": "건물 밖에 설치된 키박스의 비밀번호를 맞추고 열쇠를 꺼내세요.",
    "lblKeyCode": "🔑 키박스 비밀번호 안내",
    "lblKeyNotice": "숙박일이 가까워지면 별도 메시지로 키박스 비밀번호를 안내해 드립니다.",
    "btnCheckinGuide": "키박스 위치 사진 가이드",
    "step2Title": "2. 방문 열고 입실하기",
    "step2Desc": "열쇠를 사용해 101호 문을 열고 들어가세요. 현관에서 반드시 신발을 벗어주세요.",
    "lockWarnTitle": "주의: 수동 잠금 방식 (자동 잠금 아님)",
    "lockWarnDesc": "외출 및 퇴실 시에는 반드시 열쇠로 직접 문을 잠가주세요.",
    "step3Title": "3. [필수] 거실 태블릿에서 등록 완료하기",
    "step3Desc": "입실 후 거실에 있는 전용 태블릿(maneKEY)을 통해 본인 확인 및 체크인을 완료해 주세요.",
    "step3Tip": "※ 사전 등록을 마치신 분은 화면의 QR코드를 스캔하여 빠르게 완료할 수 있습니다.",
    "wifiTitle": "Wi-Fi 정보 및 비품 안내",
    "wifiSub": "무료 고속 Wi-Fi 및 가전 사용법",
    "lblSsid5G": "SSID (5GHz - 고속)",
    "btnCopy": "복사",
    "lblSsid24G": "SSID (2.4GHz)",
    "lblWifiPassword": "Wi-Fi 비밀번호",
    "rulesTitle": "이용 수칙 (House Rules)",
    "rulesSub": "쾌적한 숙박을 위해 반드시 지켜주세요",
    "rulePenaltyTitle": "위약금 규정 (30,000엔):",
    "rulePenaltyDesc": "이웃 주민에 대한 배려를 위해 규정 위반이나 소음 민원 발생 시 30,000엔의 위약금이 청구되며 즉시 퇴실 조치됩니다.",
    "rule1Title": "전 구역 금연",
    "rule1Desc": "실내, 발코니, 건물 공용부를 포함한 전 구역 금연(전자담배 포함)입니다.",
    "rule2Title": "20:00 이후 소음 엄금",
    "rule2Desc": "야간은 조용히 해야 하는 시간입니다. 파티 금지. 창문을 닫고 TV 및 대화 소리를 줄여주세요.",
    "rule3Title": "실내 신발 착용 금지",
    "rule3Desc": "일본 문화에 따라 현관에서 반드시 신발을 벗고 입실해 주세요.",
    "rule4Title": "미등록 인원 입실 금지",
    "rule4Desc": "예약 인원 외 외부인의 무단 입실 및 숙박은 엄격히 금지됩니다.",
    "nearbyTitle": "주변 지도 및 주차장 안내",
    "nearbySub": "인근 슈퍼마켓, 편의점 및 맛집",
    "btnGoogleMyMap": "추천 주변 지도 열기 (Google My Maps)",
    "placeParkTitle": "인근 유료 주차장",
    "placeParkTag": "전용 주차장 없음·주정차 금지",
    "placeParkDesc": "차량 이용 시 근처의 유료 동전 주차장을 이용해 주세요.",
    "btnSearchPark": "가까운 주차장 찾기",
    "placeSuperTitle": "슈퍼마켓 'KINSHO (킨쇼)'",
    "placeSuperTag": "식료품·생필품",
    "placeSuperDesc": "가장 가까운 편리한 슈퍼마켓 'KINSHO'. 신선한 식료품과 조리 식품을 구매할 수 있습니다 (도보 바로 앞).",
    "btnSearchSuper": "경로 보기",
    "placeStoreTitle": "편의점 '로손'",
    "placeStoreTag": "24시간 영업·ATM",
    "placeStoreDesc": "심야 쇼핑 및 현금 인출이 가능한 편의점 (도보 바로 앞).",
    "btnSearchStore": "경로 보기",
    "placeFoodTitle": "현지 맛집 '야로쿠 (Yaroku)'",
    "placeFoodTag": "명물 안심 돈카츠 & 오무라이스",
    "placeFoodDesc": "현지에서 대인기인 전통 양식당 '야로쿠'. 부드러운 안심 돈카츠와 오무라이스가 유명합니다.",
    "btnSearchFood": "지도에서 '야로쿠' 보기 ↗",
    "placeTakoTitle": "타코야끼 '양배추 하우스'",
    "placeTakoTag": "타코야끼·오사카 명물",
    "placeTakoDesc": "코하마 상점가에 위치한 현지 인기 타코야끼 가게. 갓 구운 따끈따끈한 오사카 명물 타코야끼를 즐겨보세요. (도보 거리)",
    "btnSearchTako": "지도에서 타코야끼 가게 보기 ↗",
    "cultureTitle": "🇯🇵 일본 숙박 매너 & 여행 팁",
    "cultureSub": "유용한 현지 에티켓 가이드",
    "cul1Title": "신발 벗는 문화",
    "cul1Desc": "현관에서 신발을 벗는 것이 일본 문화입니다. 실내에서는 슬리퍼나 맨발로 지내주세요.",
    "cul2Title": "팁 문화 없음",
    "cul2Desc": "일본의 식당이나 택시에서는 팁을 받는 문화가 없습니다. 표시된 금액만 지불하세요.",
    "cul3Title": "오사카 에스컬레이터 매너",
    "cul3Desc": "오사카에서는 에스컬레이터 이용 시 오른쪽에 서고 왼쪽을 비워두는 것이 일반적입니다.",
    "checkoutTitle": "체크아웃 절차",
    "checkoutSub": "퇴실 시 확인 사항",
    "checkoutTimeTitle": "체크아웃 시간: 오전 10:00 까지",
    "checkoutTimeDesc": "청소 스태프의 준비를 위해 체크아웃 시간을 엄수해 주시기 바랍니다.",
    "checkoutListTitle": "📋 퇴실 체크리스트",
    "coStep1": "소지품 확인: 충전기, 의류를 확인하시고 TV의 OTT 계정을 로그아웃해 주세요.",
    "coStep2": "전원/에어컨 끄기: 모든 조명, 에어컨, 난방을 끄고 창문을 잠가주세요.",
    "coStep3": "태블릿 완료: 거실 태블릿에서 '체크아웃' 완료 버튼을 눌러주세요.",
    "coStep4": "쓰레기 처리: 모아둔 쓰레기는 실내 안에 두고 퇴실해 주세요.",
    "coStep5": "문 잠금 & 열쇠 반납: 열쇠로 문을 잠그고 열쇠를 키박스에 넣은 뒤 다이얼을 돌려주세요.",
    "faqTitle": "FAQ & 고객 지원",
    "faqSub": "Troubleshooting & Support",
    "btnChatbot": "24시간 지원 챗봇 열기",
    "faq1Q": "Q. 연박 중 쓰레기가 쌓이면 어떻게 하나요?",
    "faq1A": "봉투에 모아 【건물 앞 전용 쓰레기 수거함】에 버려주세요 (일요일 제외).<br>자세한 분리수거 방법은 <a href=\"https://mastor-prog.github.io/house-guide/#garbage\" target=\"_blank\" rel=\"noopener noreferrer\" style=\"color:var(--accent-gold); text-decoration:underline; font-weight:600;\">하우스 매뉴얼 \"5. Garbage / 쓰레기 분리수거\" ↗</a> 를 참고해 주세요.",
    "faq2Q": "Q. 키박스가 열리지 않습니다",
    "faq2A": "메시지로 받으신 비밀번호를 중앙에 맞추고 커버를 열어주세요.",
    "faq3Q": "Q. 20:00 이후 늦은 도착 시?",
    "faq3A": "24시간 셀프 체크인이 가능하므로 늦은 시간 도착하셔도 괜찮습니다. 주택가이므로 이웃 주민의 수면에 방해가 되지 않도록 야외(건물 주변 및 도로)에서의 대화는 자제해 주시고, 수하물을 들어서 이동하는 등 조용히 이동해 주시기 바랍니다.",
    "sosTitle": "🆘 긴급 연락처 & 다국어 헬프데스크",
    "sosPolice": "경찰: 110",
    "sosFire": "구급·소방: 119",
    "contactBtn": "24시간 지원 챗봇 열기",
    "taxiModalTitle": "🚖 택시 기사님에게 보여주는 화면",
    "taxiModalDesc": "기사님에게 이 일본어 주소 화면을 보여주세요.",
    "taxiModalNote": "*도로가 좁으니 근처에서 하차하시는 것을 추천합니다.",
    "btnCopyAddressModal": "일본어 주소 복사하기",
    "heroDesc": "편안한 숙박을 위한 게스트 포털 가이드입니다",
    "navManual": "하우스 매뉴얼 ↗",
    "quickManual": "📖 하우스 매뉴얼",
    "btnHouseManual": "웹 하우스 매뉴얼 보기 ↗",
    "catBefore": "🛫 도착 전 안내",
    "catStay": "🏠 체류 중 안내",
    "catCheckout": "🚪 퇴실 및 지원",
    "navManualCard": "📖 하우스 매뉴얼",
    "manualTitle": "📖 WEB 하우스 매뉴얼 (House Manual)",
    "manualTag": "가전·비품·분리수거",
    "manualDesc": "에어컨, 세탁기 등 가전제품 사용법, 시설 이용 안내, 쓰레기 분리수거 수칙 등 쾌적한 체류를 위한 공식 온라인 가이드입니다.",
    "btnOpenManual": "하우스 매뉴얼 열기 ↗",
    "checkoutManualNote": "※사진이 포함된 자세한 체크아웃 절차는 하우스 매뉴얼을 참고해 주세요.",
    "btnCheckoutManual": "📖 하우스 매뉴얼 \"9. Check-out / 체크아웃\" 보기 ↗"
  }
};

    function initLanguage() {
      const userLang = navigator.language || navigator.userLanguage;
      if (userLang.startsWith('en')) {
        currentLang = 'en';
      } else if (userLang.startsWith('zh')) {
        currentLang = 'zh';
      } else if (userLang.startsWith('ko')) {
        currentLang = 'ko';
      } else {
        currentLang = 'ja';
      }
      setLanguage(currentLang);
    }

    function setLanguage(lang) {
      currentLang = lang || 'ja';
      document.querySelectorAll('.lang-btn').forEach(btn => {
        if (btn.getAttribute('data-lang') === currentLang) {
          btn.classList.add('active');
        } else {
          btn.classList.remove('active');
        }
      });

      const data = i18nData[currentLang] || i18nData.ja;

      document.querySelectorAll('[data-i18n]').forEach(el => {
        const key = el.getAttribute('data-i18n');
        if (data[key]) {
          el.innerHTML = data[key];
        }
      });
    }

    function toggleTaxiModal(show) {
      const modal = document.getElementById('taxiModal');
      if (show) {
        modal.classList.add('active');
      } else {
        modal.classList.remove('active');
      }
    }

    function copyText(text) {
      navigator.clipboard.writeText(text).then(() => {
        showToast();
      }).catch(err => {
        console.error('Copy failed', err);
      });
    }

    function copyAddress() {
      const address = "〒559-0001 大阪府大阪市住之江区粉浜3丁目7-20 フォルモント住之江 101号室";
      copyText(address);
    }

    function showToast() {
      const toast = document.getElementById('toast');
      toast.classList.add('show');
      setTimeout(() => {
        toast.classList.remove('show');
      }, 2500);
    }

    function toggleFaq(element) {
      element.classList.toggle('active');
    }

    // Initialize on page load
    document.addEventListener('DOMContentLoaded', () => {
      initLanguage();
    });
  